version: '3'
services:
  db:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: drupal_obiba
      MYSQL_ROOT_PASSWORD: 1234
    restart: always
    ports:
      - "3366:3306"
  drupal:
    depends_on:
      - db
    build: .
    ports:
      - "8888:80"
    restart: always
    extra_hosts:
        - "dockerhost:$DOCKERHOST"